### PR TITLE
Simplify properties

### LINKED ISSUE #8: Simplifying the chain type definition with named tuples
I want to suggest a simpler way to define the chain types. Instead of using defining separated types for annotated and not annotated chains, we can use a named tuple to define an extensible chain type. This way, we can avoid the complexity of handling two different types and thus simplify the interface and implementation.

The main points are:
- Define a chain type having a named tuple of properties as a field so that we can add new properties without changing the type definition.
- Make the chain type immutable to avoid unnecessary memory allocations.
- Define types for chain and residue properties to allow for different types of properties.

First, we define the property tyepss for the chain type:
```julia
abstract type AbstractProperty end

# Chain-level properties
struct ChainProperty{T} <: AbstractProperty
    value::T
end

Base.getindex(prop::ChainProperty) = prop.value

# Residue-level properties (the last dimension of the array corresponds to residues)
struct ResidueProperty{T, A <: AbstractArray{T}} <: AbstractProperty
    values::A
end

Base.getindex(prop::ResidueProperty) = prop.values
Base.getindex(prop::ResidueProperty, i::AbstractVector) = selectdim(prop.values, ndims(prop.values), i)
```
    
Then, we define the chain type as a named tuple:
```julia
const NamedProperties{names} = NamedTuple{names, <: Tuple{Vararg{AbstractProperty}}}

struct Chain{T, Ps <: NamedProperties}
    id::String
    sequence::String
    backbone::Array{T, 3}
    numbering::Vector{Int64}
    atoms::Vector{Vector{Atom{T}}}
    properties::Ps
end

Base.getproperty(chain::Chain, name::Symbol) =
    name == :id ? getfield(chain, :id) :
    name == :sequence ? getfield(chain, :sequence) :
    name == :backbone ? getfield(chain, :backbone) :
    name == :numbering ? getfield(chain, :numbering) :
    name == :atoms ? getfield(chain, :atoms) :
    name == :properties ? getfield(chain, :properties) :
    getfield(getfield(chain, :properties), name)

function Base.getindex(chain::Chain, i::AbstractVector)
    properties = map(p -> p isa ChainProperty ? ChainProperty(getindex(p)) : ResidueProperty(getindex(p, i)), chain.properties)
    Chain(chain.id, chain.sequence[i], chain.backbone[:,:,i], chain.numbering[i], chain.atoms[i], properties)
end

annotate(chain::Chain; annotations...) =
    Chain(chain.id, chain.sequence, chain.backbone, chain.numbering, chain.atoms, merge(chain.properties, annotations))
```

This works as follows:
```julia
# Create a chain with random data
chain = Chain(
    "myid",
    "ABCDEFGHIJ",
    randn(3, 3, 10),
    [1:10;],
    [Atom{Float64}[] for _ in 1:10],
    (score = ChainProperty(0.1), others = ResidueProperty(randn(10))),
)

# Select the first 5 residues
x = chain[1:5]

# Access some properties
x.id, x.sequence, x.score, x.others

# Annotate the chain with a new property
annotate(chain, label = ChainProperty("foo bar"))
```

If type stability is not a concern, we can remove the type parameter of the properties in the `Chain` type.

### PR DESCRIPTION
**Pull request by AntonOresten**
Closes #8 

I did a little more than simplifying the properties, adding an `atoms` field to `ProteinStructure`, and removing the `backbone` field from `ProteinChain`. This is breaking and intended to be pushed with a version that easily serializes to HDF5.

Could use some more unit tests.

### CODE REVIEW

**Review by bicycle1885 — COMMENTED** [review]
This looks good to me. Are you going to add the serializer to this PR?

**Comment by AntonOresten** [comment]
Yes, here it is. I currently define `ProteinChains.serialize` and `ProteinChains.deserialize` which are meant work with collections of `ProteinStructure`s, so there's currently no way to write single chains or structures. Is it worth having some `ProteinDataset <: AbstractDict{String,ProteinStructure}` type for easy indexing and unambiguous serialization IO, or are vectors good enough?

**Review by bicycle1885 — COMMENTED** [review]
I tried the serialization and deserialization pair, which works nicely. One practical thing we'll need is partial/sequential deserialization from a serialized data file because the file would be too large to deserialize in one go. I assume some interface like the following:
```julia
data = Deserializer("data.h5")

# Sequential deserialization
for structure in data
    # Do something
end

# Partial deserialization
for id in some_id_list
    structure = data[id]  # Or multiple ids if it is more efficient
    # Do something
end
```

This can be done in a separated pull request.

**Comment by AntonOresten** [comment]
Great idea with the lazy deserialization type. I might also try a corresponding "Serializer" with e.g. a `Base.delete!` method, as the current serialize `mode` keyword argument doesn't give a lot of control. Opening a PR soon!

**Pull request merged**
